name: uxcellent
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.19.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dynamic_color: ^1.6.2
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.3
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
