name: uxcellent
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.3
  dynamic_color: ^1.6.6
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/roleIcons/
    - assets/social/
